name: Push Docker to JFrog
on:
  workflow_call:
    inputs:
      docker_artifact:
        required: true
        type: string    
      docker_repository:
        required: true
        type: string
      container_name:
        required: true
        type: string
      container_version:
        required: true
        type: string
    secrets:
      JFrog_TOKEN:
        required: true
      JFrog_URL:
        required: true
      JFrog_USER:
        required: true         

jobs:
  Push-Docker-to-JFrog:
    runs-on: ubuntu-latest
    steps:
      # Setup phase
      - name: Setup JFrog
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_URL: https://${{ secrets.JFrog_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JFrog_TOKEN }}    

      - name: Login to JFrog Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://${{ secrets.JFrog_URL }}
          username: ${{ secrets.JFrog_USER }}
          password: ${{ secrets.JFrog_TOKEN }}

      - name: Test JFrog
        run: jf rt ping

      - name: Debug for ls
        run: ls -R

      - name: Fail if the given version is existing
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          if ((`jf rt search ${{ inputs.docker_repository }}/${{ inputs.container_name }}:${{ inputs.container_version }}/* 2> /dev/null | wc -c` > 4 )); then 
            exit 1
          fi

      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.docker_artifact }}

      - name: Build docker image
        run: docker build ${{ inputs.docker_artifact }} -t ${{ secrets.JFrog_URL }}/${{ inputs.docker_repository }}/${{ inputs.container_name }}:${{ inputs.container_version }}

      - name: Push docker image from master branch
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker push ${{ secrets.JFrog_URL }}/${{ inputs.docker_repository }}/${{ inputs.container_name }}:${{ inputs.container_version }}

      - name: Push docker image from non-master branch
        if: ${{ github.ref != 'refs/heads/master' }}
        run: docker push ${{ secrets.JFrog_URL }}/${{ inputs.docker_repository }}/${{ inputs.container_name }}:${{ inputs.container_version }}-beta
